//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.paygate.payhost package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.paygate.payhost
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PingRequest }
     * 
     */
    public PingRequest createPingRequest() {
        return new PingRequest();
    }

    /**
     * Create an instance of {@link PayGateAccountType }
     * 
     */
    public PayGateAccountType createPayGateAccountType() {
        return new PayGateAccountType();
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link SinglePaymentRequest }
     * 
     */
    public SinglePaymentRequest createSinglePaymentRequest() {
        return new SinglePaymentRequest();
    }

    /**
     * Create an instance of {@link CardPaymentRequestType }
     * 
     */
    public CardPaymentRequestType createCardPaymentRequestType() {
        return new CardPaymentRequestType();
    }

    /**
     * Create an instance of {@link WebPaymentRequestType }
     * 
     */
    public WebPaymentRequestType createWebPaymentRequestType() {
        return new WebPaymentRequestType();
    }

    /**
     * Create an instance of {@link TokenPaymentRequestType }
     * 
     */
    public TokenPaymentRequestType createTokenPaymentRequestType() {
        return new TokenPaymentRequestType();
    }

    /**
     * Create an instance of {@link BankPaymentRequestType }
     * 
     */
    public BankPaymentRequestType createBankPaymentRequestType() {
        return new BankPaymentRequestType();
    }

    /**
     * Create an instance of {@link SinglePaymentResponse }
     * 
     */
    public SinglePaymentResponse createSinglePaymentResponse() {
        return new SinglePaymentResponse();
    }

    /**
     * Create an instance of {@link CardPaymentResponseType }
     * 
     */
    public CardPaymentResponseType createCardPaymentResponseType() {
        return new CardPaymentResponseType();
    }

    /**
     * Create an instance of {@link WebPaymentResponseType }
     * 
     */
    public WebPaymentResponseType createWebPaymentResponseType() {
        return new WebPaymentResponseType();
    }

    /**
     * Create an instance of {@link TokenPaymentResponseType }
     * 
     */
    public TokenPaymentResponseType createTokenPaymentResponseType() {
        return new TokenPaymentResponseType();
    }

    /**
     * Create an instance of {@link BankPaymentResponseType }
     * 
     */
    public BankPaymentResponseType createBankPaymentResponseType() {
        return new BankPaymentResponseType();
    }

    /**
     * Create an instance of {@link SinglePayoutRequest }
     * 
     */
    public SinglePayoutRequest createSinglePayoutRequest() {
        return new SinglePayoutRequest();
    }

    /**
     * Create an instance of {@link CardPayoutRequestType }
     * 
     */
    public CardPayoutRequestType createCardPayoutRequestType() {
        return new CardPayoutRequestType();
    }

    /**
     * Create an instance of {@link BankPayoutRequestType }
     * 
     */
    public BankPayoutRequestType createBankPayoutRequestType() {
        return new BankPayoutRequestType();
    }

    /**
     * Create an instance of {@link WalletPayoutRequestType }
     * 
     */
    public WalletPayoutRequestType createWalletPayoutRequestType() {
        return new WalletPayoutRequestType();
    }

    /**
     * Create an instance of {@link SinglePayoutResponse }
     * 
     */
    public SinglePayoutResponse createSinglePayoutResponse() {
        return new SinglePayoutResponse();
    }

    /**
     * Create an instance of {@link CardPayoutResponseType }
     * 
     */
    public CardPayoutResponseType createCardPayoutResponseType() {
        return new CardPayoutResponseType();
    }

    /**
     * Create an instance of {@link BankPayoutResponseType }
     * 
     */
    public BankPayoutResponseType createBankPayoutResponseType() {
        return new BankPayoutResponseType();
    }

    /**
     * Create an instance of {@link WalletPayoutResponseType }
     * 
     */
    public WalletPayoutResponseType createWalletPayoutResponseType() {
        return new WalletPayoutResponseType();
    }

    /**
     * Create an instance of {@link SingleFollowUpRequest }
     * 
     */
    public SingleFollowUpRequest createSingleFollowUpRequest() {
        return new SingleFollowUpRequest();
    }

    /**
     * Create an instance of {@link QueryRequestType }
     * 
     */
    public QueryRequestType createQueryRequestType() {
        return new QueryRequestType();
    }

    /**
     * Create an instance of {@link SettleRequestType }
     * 
     */
    public SettleRequestType createSettleRequestType() {
        return new SettleRequestType();
    }

    /**
     * Create an instance of {@link RefundRequestType }
     * 
     */
    public RefundRequestType createRefundRequestType() {
        return new RefundRequestType();
    }

    /**
     * Create an instance of {@link VoidRequestType }
     * 
     */
    public VoidRequestType createVoidRequestType() {
        return new VoidRequestType();
    }

    /**
     * Create an instance of {@link SingleFollowUpResponse }
     * 
     */
    public SingleFollowUpResponse createSingleFollowUpResponse() {
        return new SingleFollowUpResponse();
    }

    /**
     * Create an instance of {@link QueryResponseType }
     * 
     */
    public QueryResponseType createQueryResponseType() {
        return new QueryResponseType();
    }

    /**
     * Create an instance of {@link SettleResponseType }
     * 
     */
    public SettleResponseType createSettleResponseType() {
        return new SettleResponseType();
    }

    /**
     * Create an instance of {@link RefundResponseType }
     * 
     */
    public RefundResponseType createRefundResponseType() {
        return new RefundResponseType();
    }

    /**
     * Create an instance of {@link VoidResponseType }
     * 
     */
    public VoidResponseType createVoidResponseType() {
        return new VoidResponseType();
    }

    /**
     * Create an instance of {@link SingleVaultRequest }
     * 
     */
    public SingleVaultRequest createSingleVaultRequest() {
        return new SingleVaultRequest();
    }

    /**
     * Create an instance of {@link CardVaultRequestType }
     * 
     */
    public CardVaultRequestType createCardVaultRequestType() {
        return new CardVaultRequestType();
    }

    /**
     * Create an instance of {@link WalletVaultRequestType }
     * 
     */
    public WalletVaultRequestType createWalletVaultRequestType() {
        return new WalletVaultRequestType();
    }

    /**
     * Create an instance of {@link LookUpVaultRequestType }
     * 
     */
    public LookUpVaultRequestType createLookUpVaultRequestType() {
        return new LookUpVaultRequestType();
    }

    /**
     * Create an instance of {@link DeleteVaultRequestType }
     * 
     */
    public DeleteVaultRequestType createDeleteVaultRequestType() {
        return new DeleteVaultRequestType();
    }

    /**
     * Create an instance of {@link SingleVaultResponse }
     * 
     */
    public SingleVaultResponse createSingleVaultResponse() {
        return new SingleVaultResponse();
    }

    /**
     * Create an instance of {@link CardVaultResponseType }
     * 
     */
    public CardVaultResponseType createCardVaultResponseType() {
        return new CardVaultResponseType();
    }

    /**
     * Create an instance of {@link WalletVaultResponseType }
     * 
     */
    public WalletVaultResponseType createWalletVaultResponseType() {
        return new WalletVaultResponseType();
    }

    /**
     * Create an instance of {@link LookUpVaultResponseType }
     * 
     */
    public LookUpVaultResponseType createLookUpVaultResponseType() {
        return new LookUpVaultResponseType();
    }

    /**
     * Create an instance of {@link DeleteVaultResponseType }
     * 
     */
    public DeleteVaultResponseType createDeleteVaultResponseType() {
        return new DeleteVaultResponseType();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link RiskType }
     * 
     */
    public RiskType createRiskType() {
        return new RiskType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link BrowserType }
     * 
     */
    public BrowserType createBrowserType() {
        return new BrowserType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ShippingDetailsType }
     * 
     */
    public ShippingDetailsType createShippingDetailsType() {
        return new ShippingDetailsType();
    }

    /**
     * Create an instance of {@link BillingDetailsType }
     * 
     */
    public BillingDetailsType createBillingDetailsType() {
        return new BillingDetailsType();
    }

    /**
     * Create an instance of {@link OrderItemType }
     * 
     */
    public OrderItemType createOrderItemType() {
        return new OrderItemType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link AcquirerInfoType }
     * 
     */
    public AcquirerInfoType createAcquirerInfoType() {
        return new AcquirerInfoType();
    }

    /**
     * Create an instance of {@link PassengerType }
     * 
     */
    public PassengerType createPassengerType() {
        return new PassengerType();
    }

    /**
     * Create an instance of {@link FlightLegType }
     * 
     */
    public FlightLegType createFlightLegType() {
        return new FlightLegType();
    }

    /**
     * Create an instance of {@link AirlineBookingDetailsType }
     * 
     */
    public AirlineBookingDetailsType createAirlineBookingDetailsType() {
        return new AirlineBookingDetailsType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link VaultDataType }
     * 
     */
    public VaultDataType createVaultDataType() {
        return new VaultDataType();
    }

    /**
     * Create an instance of {@link RedirectRequestType }
     * 
     */
    public RedirectRequestType createRedirectRequestType() {
        return new RedirectRequestType();
    }

    /**
     * Create an instance of {@link RedirectResponseType }
     * 
     */
    public RedirectResponseType createRedirectResponseType() {
        return new RedirectResponseType();
    }

    /**
     * Create an instance of {@link InstructionsResponseType }
     * 
     */
    public InstructionsResponseType createInstructionsResponseType() {
        return new InstructionsResponseType();
    }

    /**
     * Create an instance of {@link ThreeDSecureType }
     * 
     */
    public ThreeDSecureType createThreeDSecureType() {
        return new ThreeDSecureType();
    }

    /**
     * Create an instance of {@link FacilitatorType }
     * 
     */
    public FacilitatorType createFacilitatorType() {
        return new FacilitatorType();
    }

    /**
     * Create an instance of {@link RecurringType }
     * 
     */
    public RecurringType createRecurringType() {
        return new RecurringType();
    }

    /**
     * Create an instance of {@link FrequencyType }
     * 
     */
    public FrequencyType createFrequencyType() {
        return new FrequencyType();
    }

}
