//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.paygate.co.za/PayHOST", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.paygate.payhost;
