//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentMethodType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="CC"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="EW"/&gt;
 *     &lt;enumeration value="BT"/&gt;
 *     &lt;enumeration value="CV"/&gt;
 *     &lt;enumeration value="PC"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PaymentMethodType")
@XmlEnum
public enum PaymentMethodType {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Credit Card&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    CC,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Debit Card&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    DC,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;eWallet&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    EW,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Bank Transfer&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    BT,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Cash Voucher&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    CV,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Pre-Paid Card&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    PC,

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;p xmlns:sch="http://www.paygate.co.za/PayHOST" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.paygate.co.za/PayHOST" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xspg="http://www.paygate.co.za/PayHOST"&gt;Mobile Payment&lt;/p&gt;
     * </pre>
     * 
     * 
     */
    MO;

    public String value() {
        return name();
    }

    public static PaymentMethodType fromValue(String v) {
        return valueOf(v);
    }

}
