//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryTransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QueryTransactionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Authorisation"/&gt;
 *     &lt;enumeration value="Settlement"/&gt;
 *     &lt;enumeration value="Refund"/&gt;
 *     &lt;enumeration value="Payout"/&gt;
 *     &lt;enumeration value="Purchase"/&gt;
 *     &lt;enumeration value="All"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QueryTransactionType")
@XmlEnum
public enum QueryTransactionType {

    @XmlEnumValue("Authorisation")
    AUTHORISATION("Authorisation"),
    @XmlEnumValue("Settlement")
    SETTLEMENT("Settlement"),
    @XmlEnumValue("Refund")
    REFUND("Refund"),
    @XmlEnumValue("Payout")
    PAYOUT("Payout"),
    @XmlEnumValue("Purchase")
    PURCHASE("Purchase"),
    @XmlEnumValue("All")
    ALL("All");
    private final String value;

    QueryTransactionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QueryTransactionType fromValue(String v) {
        for (QueryTransactionType c: QueryTransactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
