//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CardPayoutResponse" type="{http://www.paygate.co.za/PayHOST}CardPayoutResponseType"/&gt;
 *           &lt;element name="BankPayoutResponse" type="{http://www.paygate.co.za/PayHOST}BankPayoutResponseType"/&gt;
 *           &lt;element name="WalletPayoutResponse" type="{http://www.paygate.co.za/PayHOST}WalletPayoutResponseType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardPayoutResponse",
    "bankPayoutResponse",
    "walletPayoutResponse"
})
@XmlRootElement(name = "SinglePayoutResponse")
public class SinglePayoutResponse {

    @XmlElement(name = "CardPayoutResponse")
    protected CardPayoutResponseType cardPayoutResponse;
    @XmlElement(name = "BankPayoutResponse")
    protected BankPayoutResponseType bankPayoutResponse;
    @XmlElement(name = "WalletPayoutResponse")
    protected WalletPayoutResponseType walletPayoutResponse;

    /**
     * Gets the value of the cardPayoutResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CardPayoutResponseType }
     *     
     */
    public CardPayoutResponseType getCardPayoutResponse() {
        return cardPayoutResponse;
    }

    /**
     * Sets the value of the cardPayoutResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPayoutResponseType }
     *     
     */
    public void setCardPayoutResponse(CardPayoutResponseType value) {
        this.cardPayoutResponse = value;
    }

    /**
     * Gets the value of the bankPayoutResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BankPayoutResponseType }
     *     
     */
    public BankPayoutResponseType getBankPayoutResponse() {
        return bankPayoutResponse;
    }

    /**
     * Sets the value of the bankPayoutResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankPayoutResponseType }
     *     
     */
    public void setBankPayoutResponse(BankPayoutResponseType value) {
        this.bankPayoutResponse = value;
    }

    /**
     * Gets the value of the walletPayoutResponse property.
     * 
     * @return
     *     possible object is
     *     {@link WalletPayoutResponseType }
     *     
     */
    public WalletPayoutResponseType getWalletPayoutResponse() {
        return walletPayoutResponse;
    }

    /**
     * Sets the value of the walletPayoutResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WalletPayoutResponseType }
     *     
     */
    public void setWalletPayoutResponse(WalletPayoutResponseType value) {
        this.walletPayoutResponse = value;
    }

}
