//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CardPaymentRequest" type="{http://www.paygate.co.za/PayHOST}CardPaymentRequestType"/&gt;
 *           &lt;element name="WebPaymentRequest" type="{http://www.paygate.co.za/PayHOST}WebPaymentRequestType"/&gt;
 *           &lt;element name="TokenPaymentRequest" type="{http://www.paygate.co.za/PayHOST}TokenPaymentRequestType"/&gt;
 *           &lt;element name="BankPaymentRequest" type="{http://www.paygate.co.za/PayHOST}BankPaymentRequestType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardPaymentRequest",
    "webPaymentRequest",
    "tokenPaymentRequest",
    "bankPaymentRequest"
})
@XmlRootElement(name = "SinglePaymentRequest")
public class SinglePaymentRequest {

    @XmlElement(name = "CardPaymentRequest")
    protected CardPaymentRequestType cardPaymentRequest;
    @XmlElement(name = "WebPaymentRequest")
    protected WebPaymentRequestType webPaymentRequest;
    @XmlElement(name = "TokenPaymentRequest")
    protected TokenPaymentRequestType tokenPaymentRequest;
    @XmlElement(name = "BankPaymentRequest")
    protected BankPaymentRequestType bankPaymentRequest;

    /**
     * Gets the value of the cardPaymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentRequestType }
     *     
     */
    public CardPaymentRequestType getCardPaymentRequest() {
        return cardPaymentRequest;
    }

    /**
     * Sets the value of the cardPaymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentRequestType }
     *     
     */
    public void setCardPaymentRequest(CardPaymentRequestType value) {
        this.cardPaymentRequest = value;
    }

    /**
     * Gets the value of the webPaymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link WebPaymentRequestType }
     *     
     */
    public WebPaymentRequestType getWebPaymentRequest() {
        return webPaymentRequest;
    }

    /**
     * Sets the value of the webPaymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebPaymentRequestType }
     *     
     */
    public void setWebPaymentRequest(WebPaymentRequestType value) {
        this.webPaymentRequest = value;
    }

    /**
     * Gets the value of the tokenPaymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TokenPaymentRequestType }
     *     
     */
    public TokenPaymentRequestType getTokenPaymentRequest() {
        return tokenPaymentRequest;
    }

    /**
     * Sets the value of the tokenPaymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenPaymentRequestType }
     *     
     */
    public void setTokenPaymentRequest(TokenPaymentRequestType value) {
        this.tokenPaymentRequest = value;
    }

    /**
     * Gets the value of the bankPaymentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link BankPaymentRequestType }
     *     
     */
    public BankPaymentRequestType getBankPaymentRequest() {
        return bankPaymentRequest;
    }

    /**
     * Sets the value of the bankPaymentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankPaymentRequestType }
     *     
     */
    public void setBankPaymentRequest(BankPaymentRequestType value) {
        this.bankPaymentRequest = value;
    }

}
