//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.22 at 06:53:12 PM SAST 
//


package za.co.paygate.payhost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CardPaymentResponse" type="{http://www.paygate.co.za/PayHOST}CardPaymentResponseType"/&gt;
 *           &lt;element name="WebPaymentResponse" type="{http://www.paygate.co.za/PayHOST}WebPaymentResponseType"/&gt;
 *           &lt;element name="TokenPaymentResponse" type="{http://www.paygate.co.za/PayHOST}TokenPaymentResponseType"/&gt;
 *           &lt;element name="BankPaymentResponse" type="{http://www.paygate.co.za/PayHOST}BankPaymentResponseType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardPaymentResponse",
    "webPaymentResponse",
    "tokenPaymentResponse",
    "bankPaymentResponse"
})
@XmlRootElement(name = "SinglePaymentResponse")
public class SinglePaymentResponse {

    @XmlElement(name = "CardPaymentResponse")
    protected CardPaymentResponseType cardPaymentResponse;
    @XmlElement(name = "WebPaymentResponse")
    protected WebPaymentResponseType webPaymentResponse;
    @XmlElement(name = "TokenPaymentResponse")
    protected TokenPaymentResponseType tokenPaymentResponse;
    @XmlElement(name = "BankPaymentResponse")
    protected BankPaymentResponseType bankPaymentResponse;

    /**
     * Gets the value of the cardPaymentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CardPaymentResponseType }
     *     
     */
    public CardPaymentResponseType getCardPaymentResponse() {
        return cardPaymentResponse;
    }

    /**
     * Sets the value of the cardPaymentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardPaymentResponseType }
     *     
     */
    public void setCardPaymentResponse(CardPaymentResponseType value) {
        this.cardPaymentResponse = value;
    }

    /**
     * Gets the value of the webPaymentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link WebPaymentResponseType }
     *     
     */
    public WebPaymentResponseType getWebPaymentResponse() {
        return webPaymentResponse;
    }

    /**
     * Sets the value of the webPaymentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebPaymentResponseType }
     *     
     */
    public void setWebPaymentResponse(WebPaymentResponseType value) {
        this.webPaymentResponse = value;
    }

    /**
     * Gets the value of the tokenPaymentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link TokenPaymentResponseType }
     *     
     */
    public TokenPaymentResponseType getTokenPaymentResponse() {
        return tokenPaymentResponse;
    }

    /**
     * Sets the value of the tokenPaymentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenPaymentResponseType }
     *     
     */
    public void setTokenPaymentResponse(TokenPaymentResponseType value) {
        this.tokenPaymentResponse = value;
    }

    /**
     * Gets the value of the bankPaymentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link BankPaymentResponseType }
     *     
     */
    public BankPaymentResponseType getBankPaymentResponse() {
        return bankPaymentResponse;
    }

    /**
     * Sets the value of the bankPaymentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankPaymentResponseType }
     *     
     */
    public void setBankPaymentResponse(BankPaymentResponseType value) {
        this.bankPaymentResponse = value;
    }

}
